### ISSUE TITLE
Can't have multiple content types for the same url+method

### ISSUE THREAD

**Issue by Neppord** [paketphp/fram#1]
When doing a request and setting the `Accept` header I want Fram to pick a suitable handler an view pair for that content typ if it is configured.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

Example API

```php
$router = new SimpleRouter(
    ['GET' => [
        '/users/' => [UsersHtmlView::class, UsersJsonView::class]
    ]], View404::class, new DefaultViewFactory()
);
$fram = new Fram($router, new HtmlViewHandler(), new JsonViewHandler());
```

**Comment by tored** [comment]
For this you have two alternatives. The first is to implement your own `Router`. 

One option is to use FastRoute as backend and set an arrays as handler per FastRoute route & then make your router pick one depending on header.

Another option is to implement simple header `Router` that picks either the HtmlRouter or the JsonRouter.

Second alternative is to use internal redirects, the `Router` sets the `Route` to an initial view and then that view redirects to the correct view.

(Fram API has changed since you wrote the issue)

```php
$router = new SimpleRouter(
    ['GET' => [
        '/users/' => UsersView::class
    ]],  );
$fram = new Fram(new DefaultViewFactory(), $router, new HtmlViewHandler(), new JsonViewHandler());

final class UsersView implements SimpleView
{
    public function render(Route $route)
    {
        if (...) {
            return $route->withViewClass(UsersHtmlView::class);
        }
        return $route->withViewClass(UsersJsonView::class);
    }
}
```
